/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LoadingRouteImport } from './routes/loading'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as IncidentsRouteImport } from './routes/incidents'
import { Route as AlertingRouteImport } from './routes/alerting'
import { Route as IndexRouteImport } from './routes/index'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LoadingRoute = LoadingRouteImport.update({
  id: '/loading',
  path: '/loading',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsRoute = IncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertingRoute = AlertingRouteImport.update({
  id: '/alerting',
  path: '/alerting',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerting': typeof AlertingRoute
  '/incidents': typeof IncidentsRoute
  '/landing': typeof LandingRoute
  '/loading': typeof LoadingRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/services': typeof ServicesRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerting': typeof AlertingRoute
  '/incidents': typeof IncidentsRoute
  '/landing': typeof LandingRoute
  '/loading': typeof LoadingRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/services': typeof ServicesRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerting': typeof AlertingRoute
  '/incidents': typeof IncidentsRoute
  '/landing': typeof LandingRoute
  '/loading': typeof LoadingRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/services': typeof ServicesRoute
  '/users': typeof UsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerting'
    | '/incidents'
    | '/landing'
    | '/loading'
    | '/login'
    | '/logs'
    | '/services'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerting'
    | '/incidents'
    | '/landing'
    | '/loading'
    | '/login'
    | '/logs'
    | '/services'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/alerting'
    | '/incidents'
    | '/landing'
    | '/loading'
    | '/login'
    | '/logs'
    | '/services'
    | '/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertingRoute: typeof AlertingRoute
  IncidentsRoute: typeof IncidentsRoute
  LandingRoute: typeof LandingRoute
  LoadingRoute: typeof LoadingRoute
  LoginRoute: typeof LoginRoute
  LogsRoute: typeof LogsRoute
  ServicesRoute: typeof ServicesRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loading': {
      id: '/loading'
      path: '/loading'
      fullPath: '/loading'
      preLoaderRoute: typeof LoadingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents': {
      id: '/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof IncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerting': {
      id: '/alerting'
      path: '/alerting'
      fullPath: '/alerting'
      preLoaderRoute: typeof AlertingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertingRoute: AlertingRoute,
  IncidentsRoute: IncidentsRoute,
  LandingRoute: LandingRoute,
  LoadingRoute: LoadingRoute,
  LoginRoute: LoginRoute,
  LogsRoute: LogsRoute,
  ServicesRoute: ServicesRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
